name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Packages
      run: |
        sudo apt-get update
        sudo apt-get install libpam0g-dev libssl-dev
    - name: Setup Test Env
      run: |
        ssh-agent -a /tmp/ssh-agent
        export SSH_AUTH_SOCK=/tmp/ssh-agent
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: |
        ssh-keygen -t ecdsa -b 521 -f $HOME/.ssh/id_ecdsa521
        ssh-add $HOME/.ssh/id_ecdsa521
        
        cargo test --verbose
