name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      SSH_AUTH_SOCK: /tmp/ssh-agent.sock
    steps:
    - name: Install Packages
      run: |
        sudo apt-get update
        sudo apt-get install libpam0g-dev libssl-dev
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: |
        ssh-agent -a $SSH_AUTH_SOCK
        ssh-keygen -t ecdsa -b 521 -f $HOME/.ssh/id_ecdsa521
        ssh-keygen -t ecdsa -b 384 -f $HOME/.ssh/id_ecdsa384
        ssh-keygen -t ecdsa -b 256 -f $HOME/.ssh/id_ecdsa256
        ssh-keygen -t ed25519 -f $HOME/.ssh/id_ed25519
        ssh-keygen -t rsa -f $HOME/.ssh/id_rsa
        ssh-keygen -t dsa -f $HOME/.ssh/id_dsa
        ssh-add $HOME/.ssh/id_ecdsa521
        ssh-add $HOME/.ssh/id_ecdsa384
        ssh-add $HOME/.ssh/id_ecdsa256
        ssh-add $HOME/.ssh/id_ed25519
        ssh-add $HOME/.ssh/id_rsa
        ssh-add $HOME/.ssh/id_dsa
        cp $HOME/.ssh/id_rsa.pub $HOME/.ssh/authorized_keys
        
        cargo test --verbose
